version: '3'
    
services:
  backend:
    container_name: recipe_backend
    build: ./
    expose:
        - 5000
    ports:
        - 5000:5000
    volumes:
        - ./:/project
    environment:
        - FLASK_ENV=development
        - FLASK_APP=app.py
        - FLASK_DEBUG=1
    
